In [1]:
from google.colab import files
uploaded = files.upload()

Saving assignment.zip to assignment.zip

In [2]:
!unzip -q assignment.zip

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df = pd.read_csv('train.csv')

In [12]:
df.head(5)

,age,workclass,fnlwgt,education,education_num,marital_status,occupation,relationship,race,gender,capital_gain,capital_loss,hours_per_week,native_country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [6]:
df.education.unique()

array(['Bachelors', 'HS-grad', '11th', 'Masters', '9th', 'Some-college',
       'Assoc-acdm', 'Assoc-voc', '7th-8th', 'Doctorate', 'Prof-school',
       '5th-6th', '10th', '1st-4th', 'Preschool', '12th'], dtype=object)

In [7]:
df.education.value_counts()

education
HS-grad         10501
Some-college     7291
Bachelors        5355
Masters          1723
Assoc-voc        1382
11th             1175
Assoc-acdm       1067
10th              933
7th-8th           646
Prof-school       576
9th               514
12th              433
Doctorate         413
5th-6th           333
1st-4th           168
Preschool          51
Name: count, dtype: int64

In [8]:
df.occupation.value_counts()

occupation
Prof-specialty       4140
Craft-repair         4099
Exec-managerial      4066
Adm-clerical         3770
Sales                3650
Other-service        3295
Machine-op-inspct    2002
Transport-moving     1597
Handlers-cleaners    1370
Farming-fishing       994
Tech-support          928
Protective-serv       649
Priv-house-serv       149
Armed-Forces            9
Name: count, dtype: int64

In [9]:
df.marital_status.value_counts()

marital_status
Married-civ-spouse       14976
Never-married            10683
Divorced                  4443
Separated                 1025
Widowed                    993
Married-spouse-absent      418
Married-AF-spouse           23
Name: count, dtype: int64

In [5]:
df2 = pd.concat([df.drop('occupation', axis =1 ), pd.get_dummies(df['education'], prefix='education')], axis=1)

In [27]:
df2

,age,fnlwgt,education_num,gender,capital_gain,capital_loss,hours_per_week,income,education_10th,education_11th,...,native_country_Portugal,native_country_Puerto-Rico,native_country_Scotland,native_country_South,native_country_Taiwan,native_country_Thailand,native_country_Trinadad&Tobago,native_country_United-States,native_country_Vietnam,native_country_Yugoslavia
0,39,77516,13,Male,2174,0,40,<=50K,False,False,...,False,False,False,False,False,False,False,True,False,False
1,50,83311,13,Male,0,0,13,<=50K,False,False,...,False,False,False,False,False,False,False,True,False,False
2,38,215646,9,Male,0,0,40,<=50K,False,False,...,False,False,False,False,False,False,False,True,False,False
3,53,234721,7,Male,0,0,40,<=50K,False,True,...,False,False,False,False,False,False,False,True,False,False
4,28,338409,13,Female,0,0,40,<=50K,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,257302,12,Female,0,0,38,<=50K,False,False,...,False,False,False,False,False,False,False,True,False,False
32557,40,154374,9,Male,0,0,40,>50K,False,False,...,False,False,False,False,False,False,False,True,False,False
32558,58,151910,9,Female,0,0,40,<=50K,False,False,...,False,False,False,False,False,False,False,True,False,False
32559,22,201490,9,Male,0,0,20,<=50K,False,False,...,False,False,False,False,False,False,False,True,False,False
32560,52,287927,9,Female,15024,0,40,>50K,False,False,...,False,False,False,False,False,False,False,True,False,False

In [6]:
df2 = pd.concat([df2.drop('marital_status', axis =1 ), pd.get_dummies(df2['marital_status'], prefix='marital_status')], axis=1)
df2 = pd.concat([df2.drop('relationship', axis =1 ), pd.get_dummies(df2['relationship'], prefix='relationship')], axis=1)
df2 = pd.concat([df2.drop('race', axis =1 ), pd.get_dummies(df2['race'], prefix='race')], axis=1)
df2 = pd.concat([df2.drop('workclass', axis =1 ), pd.get_dummies(df2['workclass'], prefix='workclass')], axis=1)
df2 = pd.concat([df2.drop('native_country', axis =1 ), pd.get_dummies(df2['native_country'], prefix='native_country')], axis=1)
df2 = df2.drop('education', axis =1)

In [25]:
df2.head(5)

,age,fnlwgt,education_num,gender,capital_gain,capital_loss,hours_per_week,income,education_10th,education_11th,...,native_country_Portugal,native_country_Puerto-Rico,native_country_Scotland,native_country_South,native_country_Taiwan,native_country_Thailand,native_country_Trinadad&Tobago,native_country_United-States,native_country_Vietnam,native_country_Yugoslavia
0,39,77516,13,Male,2174,0,40,<=50K,False,False,...,False,False,False,False,False,False,False,True,False,False
1,50,83311,13,Male,0,0,13,<=50K,False,False,...,False,False,False,False,False,False,False,True,False,False
2,38,215646,9,Male,0,0,40,<=50K,False,False,...,False,False,False,False,False,False,False,True,False,False
3,53,234721,7,Male,0,0,40,<=50K,False,True,...,False,False,False,False,False,False,False,True,False,False
4,28,338409,13,Female,0,0,40,<=50K,False,False,...,False,False,False,False,False,False,False,False,False,False

In [7]:
df2['gender'] = df2['gender'].apply(lambda x: 1 if x == 'Male' else 0)
df2['income'] = df2['income'].apply(lambda x: 1 if x == '>50K' else 0)

In [8]:
df2

,age,fnlwgt,education_num,gender,capital_gain,capital_loss,hours_per_week,income,education_10th,education_11th,...,native_country_Portugal,native_country_Puerto-Rico,native_country_Scotland,native_country_South,native_country_Taiwan,native_country_Thailand,native_country_Trinadad&Tobago,native_country_United-States,native_country_Vietnam,native_country_Yugoslavia
0,39,77516,13,1,2174,0,40,0,False,False,...,False,False,False,False,False,False,False,True,False,False
1,50,83311,13,1,0,0,13,0,False,False,...,False,False,False,False,False,False,False,True,False,False
2,38,215646,9,1,0,0,40,0,False,False,...,False,False,False,False,False,False,False,True,False,False
3,53,234721,7,1,0,0,40,0,False,True,...,False,False,False,False,False,False,False,True,False,False
4,28,338409,13,0,0,0,40,0,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,27,257302,12,0,0,0,38,0,False,False,...,False,False,False,False,False,False,False,True,False,False
32557,40,154374,9,1,0,0,40,1,False,False,...,False,False,False,False,False,False,False,True,False,False
32558,58,151910,9,0,0,0,40,0,False,False,...,False,False,False,False,False,False,False,True,False,False
32559,22,201490,9,1,0,0,20,0,False,False,...,False,False,False,False,False,False,False,True,False,False
32560,52,287927,9,0,15024,0,40,1,False,False,...,False,False,False,False,False,False,False,True,False,False

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

train, test = train_test_split(df2, test_size=0.2, random_state=42)

In [10]:
train

,age,fnlwgt,education_num,gender,capital_gain,capital_loss,hours_per_week,income,education_10th,education_11th,...,native_country_Portugal,native_country_Puerto-Rico,native_country_Scotland,native_country_South,native_country_Taiwan,native_country_Thailand,native_country_Trinadad&Tobago,native_country_United-States,native_country_Vietnam,native_country_Yugoslavia
5514,33,198183,13,0,0,0,50,1,False,False,...,False,False,False,False,False,False,False,True,False,False
19777,36,86459,11,1,0,1887,50,1,False,False,...,False,False,False,False,False,False,False,True,False,False
10781,58,203039,5,1,0,0,40,0,False,False,...,False,False,False,False,False,False,False,True,False,False
32240,21,180190,11,1,0,0,46,0,False,False,...,False,False,False,False,False,False,False,True,False,False
9876,27,279872,10,1,0,0,40,0,False,False,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29802,47,359461,13,1,0,0,40,0,False,False,...,False,False,False,False,False,False,False,True,False,False
5390,31,147215,8,0,0,0,21,0,False,False,...,False,False,False,False,False,False,False,True,False,False
860,18,216284,7,0,0,0,20,0,False,True,...,False,False,False,False,False,False,False,True,False,False
15795,50,54261,9,1,0,0,84,0,False,False,...,False,False,False,False,False,False,False,True,False,False
23654,34,127651,13,1,0,0,60,0,False,False,...,False,False,False,False,False,False,False,True,False,False

In [11]:
train_x = train.drop('income', axis =1)
train_y = train['income']
test_x = test.drop('income', axis =1)
test_y = test['income']

In [12]:
forest = RandomForestClassifier(n_estimators=100)
forest.fit(train_x, train_y)

RandomForestClassifier()

In [13]:
forest.score(test_x, test_y)

0.8486104713649624

In [14]:
from sklearn.metrics import confusion_matrix
confusion_matrix(test_y, forest.predict(test_x))

array([[4559,  383],
       [ 603,  968]])

In [15]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV

param_grid = {
    'n_estimators': [50, 100, 150,],
    'max_depth': [10, 20 , 30 , None],
    'max_features': ['auto', 'sqrt', 'log2'],
    'min_samples_split': [2, 5, 10],
}
grid_search = GridSearchCV(forest, param_grid, cv=5, scoring='accuracy')
grid_search.fit(train_x, train_y)

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py:425: FitFailedWarning:
180 fits failed out of a total of 540.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
180 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_validation.py", line 729, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.10/dist-packages/sklearn/base.py", line 1145, in wrapper
    estimator._validate_params()
  File "/usr/local/lib/python3.10/dist-packages/sklearn/base.py", line 638, in _validate_params
    validate_parameter_constraints(
  File "/usr/local/lib/python3.10/dist-packages/sklearn/utils/_param_validation.py", line 96, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestClassifier must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_search.py:979: UserWarning: One or more of the test scores are non-finite: [       nan        nan        nan        nan        nan        nan
        nan        nan        nan 0.85369338 0.85377016 0.85430764
 0.85388541 0.85392366 0.85361667 0.85319434 0.85377017 0.85434603
 0.84950887 0.85039185 0.84954714 0.85008469 0.85066055 0.84939359
 0.85119806 0.85062218 0.85004623        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.85749401 0.85780113 0.85853054 0.85799313 0.85845375 0.85883762
 0.85814675 0.8583385  0.85975905 0.85630386 0.85653432 0.85722539
 0.85668788 0.85676461 0.85699498 0.85668781 0.85668789 0.85687973
        nan        nan        nan        nan        nan        nan
        nan        nan        nan 0.85250325 0.85319431 0.85380854
 0.85607355 0.85657251 0.85687967 0.85626552 0.85853066 0.85868416
 0.85392377 0.85476833 0.8541541  0.85503695 0.85703331 0.85588163
 0.85638066 0.85745556 0.85757073        nan        nan        nan
        nan        nan        nan        nan        nan        nan
 0.84805004 0.84970088 0.84785815 0.85089089 0.85181238 0.85384703
 0.85346304 0.85449959 0.8538854  0.84632248 0.84670633 0.84766611
 0.84973932 0.85066066 0.84981603 0.8541925  0.85346303 0.85488356]
  warnings.warn(

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'max_depth': [10, 20, 30, None],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'min_samples_split': [2, 5, 10],
                         'n_estimators': [50, 100, 150]},
             scoring='accuracy')

In [23]:
grid_search.best_estimator_

RandomForestClassifier(max_depth=20, min_samples_split=10, n_estimators=150)

In [24]:
forest_best = grid_search.best_estimator_

In [25]:
forest_best.score(test_x, test_y)

0.8604329801934593

In [26]:
import pickle
pickle.dump(forest_best, open('annual_incomemodel.pkl', 'wb'))